import pptxgen from "pptxgenjs";

export const generatePpt = async (data) => {
  const ppt = new pptxgen();

  // ============================================================
  // THEME SYSTEM — pick a palette instead of hardcoding one
  // ============================================================

  const THEMES = [
    {
      name: "indigo",
      primary: "6366F1",
      primaryDark: "4338CA",
      accent: "F59E0B",
      dark: "0F172A",
      text: "1E293B",
      muted: "64748B",
      light: "F8FAFC",
      border: "E2E8F0",
      white: "FFFFFF",
    },
    {
      name: "emerald",
      primary: "10B981",
      primaryDark: "047857",
      accent: "F97316",
      dark: "0B1E17",
      text: "1C2B24",
      muted: "5B7267",
      light: "F5FBF8",
      border: "DCEEE6",
      white: "FFFFFF",
    },
    {
      name: "sunset",
      primary: "F97316",
      primaryDark: "C2410C",
      accent: "6366F1",
      dark: "1F1410",
      text: "2B211B",
      muted: "78675C",
      light: "FFF8F3",
      border: "F1E1D3",
      white: "FFFFFF",
    },
    {
      name: "ocean",
      primary: "0EA5E9",
      primaryDark: "0369A1",
      accent: "EAB308",
      dark: "071A26",
      text: "132430",
      muted: "5C7484",
      light: "F3FAFE",
      border: "DCEEF8",
      white: "FFFFFF",
    },
    {
      name: "rose",
      primary: "F43F5E",
      primaryDark: "BE123C",
      accent: "0EA5E9",
      dark: "1F0B10",
      text: "2B1418",
      muted: "7A5A61",
      light: "FFF5F6",
      border: "F5DEE1",
      white: "FFFFFF",
    },
  ];

  const pickTheme = () => {
    if (data?.theme) {
      const match = THEMES.find((t) => t.name === data.theme);
      if (match) return match;
    }
    // Deterministic per-title pick so regenerating the same topic
    // doesn't reshuffle colors, but different topics look different.
    const str = data?.title || "default";
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = (hash * 31 + str.charCodeAt(i)) >>> 0;
    }
    return THEMES[hash % THEMES.length];
  };

  const THEME = pickTheme();

  const HEAD_FONT = "Poppins";
  const BODY_FONT = "Aptos";

  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "VortexAI";
  ppt.company = "VortexAI";
  ppt.subject = data?.title || "AI Generated Presentation";
  ppt.title = data?.title || "AI Generated Presentation";
  ppt.lang = "en-US";

  ppt.theme = {
    headFontFace: HEAD_FONT,
    bodyFontFace: BODY_FONT,
    lang: "en-US",
  };

  ppt.defineSlideMaster({
    title: "MASTER",
    background: { color: THEME.white },
    objects: [
      {
        rect: {
          x: 0,
          y: 0,
          w: 13.333,
          h: 0.08,
          fill: { color: THEME.primary },
          line: { color: THEME.primary },
        },
      },
      {
        text: {
          text: "Generated by VortexAI",
          options: {
            x: 0.65,
            y: 7.05,
            w: 3,
            h: 0.2,
            fontFace: BODY_FONT,
            fontSize: 8,
            color: THEME.muted,
            margin: 0,
          },
        },
      },
    ],
  });

  // ============================================================
  // HELPERS
  // ============================================================

  const addSlideNumber = (slide, current, total) => {
    slide.addText(
      `${String(current).padStart(2, "0")} / ${String(total).padStart(2, "0")}`,
      {
        x: 11.4,
        y: 7.03,
        w: 1.15,
        h: 0.2,
        fontFace: BODY_FONT,
        fontSize: 8,
        color: THEME.muted,
        align: "right",
        margin: 0,
      },
    );
  };

  const addEyebrow = (slide, label) => {
    slide.addShape(ppt.ShapeType.rect, {
      x: 0.7,
      y: 0.5,
      w: 0.32,
      h: 0.14,
      fill: { color: THEME.primary },
      line: { color: THEME.primary },
    });
    slide.addText(label.toUpperCase(), {
      x: 1.08,
      y: 0.4,
      w: 4,
      h: 0.3,
      fontFace: HEAD_FONT,
      fontSize: 11,
      bold: true,
      color: THEME.primaryDark,
      charSpacing: 2,
      margin: 0,
    });
  };

  const addTitle = (slide, title, subtitle = null, eyebrow = null) => {
    if (eyebrow) addEyebrow(slide, eyebrow);

    slide.addText(title, {
      x: 0.7,
      y: eyebrow ? 0.75 : 0.55,
      w: 11.8,
      h: 0.55,
      fontFace: HEAD_FONT,
      fontSize: 26,
      bold: true,
      color: THEME.dark,
      margin: 0,
      breakLine: false,
      fit: "shrink",
    });

    if (subtitle) {
      slide.addText(subtitle, {
        x: 0.72,
        y: 1.35,
        w: 11,
        h: 0.35,
        fontFace: BODY_FONT,
        fontSize: 12,
        color: THEME.muted,
        margin: 0,
        fit: "shrink",
      });
    }

    slide.addShape(ppt.ShapeType.line, {
      x: 0.7,
      y: subtitle ? 1.78 : 1.4,
      w: 11.9,
      h: 0,
      line: { color: THEME.border, width: 1 },
    });
  };

  // Numbered "badge" bullets instead of plain dots — reads as designed,
  // not like a default template. Falls back gracefully for long lists.
  const addBadgeBullets = (slide, items, startY, maxH) => {
    const rowH = Math.min(0.85, (maxH - 0.1) / Math.max(items.length, 1));
    const fontSize = items.length > 6 ? 13 : items.length > 4 ? 15 : 17;

    items.forEach((item, i) => {
      const y = startY + i * rowH;

      slide.addShape(ppt.ShapeType.ellipse, {
        x: 0.9,
        y: y + 0.05,
        w: 0.34,
        h: 0.34,
        fill: { color: i % 2 === 0 ? THEME.primary : THEME.accent },
        line: { color: THEME.white, width: 0 },
      });
      slide.addText(String(i + 1).padStart(2, "0"), {
        x: 0.9,
        y: y + 0.05,
        w: 0.34,
        h: 0.34,
        fontFace: HEAD_FONT,
        fontSize: 10,
        bold: true,
        color: THEME.white,
        align: "center",
        valign: "mid",
        margin: 0,
      });

      slide.addText(String(item), {
        x: 1.42,
        y,
        w: 10.3,
        h: rowH,
        fontFace: BODY_FONT,
        fontSize,
        color: THEME.text,
        valign: "mid",
        margin: 0,
        fit: "shrink",
      });
    });
  };

  // Two-column variant for denser slides (>5 bullets)
  const addTwoColumnBullets = (slide, items, startY, maxH) => {
    const half = Math.ceil(items.length / 2);
    const left = items.slice(0, half);
    const right = items.slice(half);
    const rowH = Math.min(0.9, (maxH - 0.1) / Math.max(half, 1));

    const renderCol = (col, xOffset) => {
      col.forEach((item, i) => {
        const y = startY + i * rowH;
        slide.addShape(ppt.ShapeType.rect, {
          x: xOffset,
          y: y + 0.12,
          w: 0.06,
          h: 0.32,
          fill: { color: THEME.primary },
          line: { color: THEME.primary },
        });
        slide.addText(String(item), {
          x: xOffset + 0.25,
          y,
          w: 5.15,
          h: rowH,
          fontFace: BODY_FONT,
          fontSize: 15,
          color: THEME.text,
          valign: "mid",
          margin: 0,
          fit: "shrink",
        });
      });
    };

    renderCol(left, 0.95);
    renderCol(right, 6.65);
  };

  // Big-number highlight slide — used when slideData.stat is present
  const addStatSlide = (slideData, index, total) => {
    const slide = ppt.addSlide("MASTER");
    addTitle(slide, slideData.title || "Highlight", null, `Section ${index}`);

    slide.addText(String(slideData.stat), {
      x: 0.7,
      y: 2.1,
      w: 5.5,
      h: 1.8,
      fontFace: HEAD_FONT,
      fontSize: 64,
      bold: true,
      color: THEME.primary,
      margin: 0,
      fit: "shrink",
    });

    if (slideData.statLabel) {
      slide.addText(String(slideData.statLabel), {
        x: 0.75,
        y: 3.85,
        w: 5.3,
        h: 0.6,
        fontFace: BODY_FONT,
        fontSize: 15,
        color: THEME.muted,
        margin: 0,
        fit: "shrink",
      });
    }

    if (Array.isArray(slideData.bullets) && slideData.bullets.length) {
      slide.addShape(ppt.ShapeType.rect, {
        x: 6.9,
        y: 2.0,
        w: 0.02,
        h: 3.2,
        fill: { color: THEME.border },
        line: { color: THEME.border },
      });
      addBadgeBullets(slide, slideData.bullets.slice(0, 4), 2.1, 3.0);
    }

    addSlideNumber(slide, index, total);
  };

  // Quote / callout slide — used when slideData.quote is present
  const addQuoteSlide = (slideData, index, total) => {
    const slide = ppt.addSlide();
    slide.background = { color: THEME.dark };

    slide.addShape(ppt.ShapeType.rect, {
      x: 0.85,
      y: 1.7,
      w: 0.9,
      h: 0.9,
      fill: { color: THEME.primary, transparency: 20 },
      line: { color: THEME.primary, transparency: 100 },
    });
    slide.addText('"', {
      x: 0.85,
      y: 1.55,
      w: 0.9,
      h: 0.9,
      fontFace: HEAD_FONT,
      fontSize: 48,
      bold: true,
      color: THEME.white,
      align: "center",
      valign: "mid",
      margin: 0,
    });

    slide.addText(String(slideData.quote), {
      x: 1.0,
      y: 2.7,
      w: 10.5,
      h: 2.0,
      fontFace: HEAD_FONT,
      fontSize: 26,
      italic: true,
      color: THEME.white,
      margin: 0,
      fit: "shrink",
    });

    if (slideData.attribution) {
      slide.addText(`— ${slideData.attribution}`, {
        x: 1.0,
        y: 4.8,
        w: 10.5,
        h: 0.4,
        fontFace: BODY_FONT,
        fontSize: 13,
        color: "94A3B8",
        margin: 0,
      });
    }

    addSlideNumber(slide, index, total);
  };

  // ============================================================
  // COVER SLIDE
  // ============================================================

  const addCover = () => {
    const slide = ppt.addSlide();
    slide.background = { color: THEME.dark };

    slide.addShape(ppt.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 0.12,
      h: 7.5,
      fill: { color: THEME.primary },
      line: { color: THEME.primary },
    });
    slide.addShape(ppt.ShapeType.rect, {
      x: 10.8,
      y: 0,
      w: 2.53,
      h: 7.5,
      fill: { color: THEME.primaryDark, transparency: 15 },
      line: { color: THEME.primaryDark, transparency: 100 },
    });
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 10.4,
      y: -1.2,
      w: 3.6,
      h: 3.6,
      fill: { color: THEME.accent, transparency: 75 },
      line: { color: THEME.accent, transparency: 100 },
    });

    slide.addText("VORTEXAI", {
      x: 0.85,
      y: 0.75,
      w: 3,
      h: 0.3,
      fontFace: HEAD_FONT,
      fontSize: 12,
      bold: true,
      color: "A5B4FC",
      charSpacing: 2,
      margin: 0,
    });

    slide.addText(data?.title || "AI Generated Presentation", {
      x: 0.85,
      y: 2.1,
      w: 9.4,
      h: 1.3,
      fontFace: HEAD_FONT,
      fontSize: 38,
      bold: true,
      color: THEME.white,
      margin: 0,
      valign: "mid",
      fit: "shrink",
    });

    if (data?.subtitle) {
      slide.addText(data.subtitle, {
        x: 0.88,
        y: 3.65,
        w: 8.7,
        h: 0.8,
        fontFace: BODY_FONT,
        fontSize: 17,
        color: "CBD5E1",
        margin: 0,
        fit: "shrink",
      });
    }

    slide.addText(`${data?.slides?.length || 0} sections`, {
      x: 0.88,
      y: 6.55,
      w: 2.5,
      h: 0.3,
      fontFace: BODY_FONT,
      fontSize: 10,
      color: "94A3B8",
      margin: 0,
    });

    slide.addText("AI-powered presentation", {
      x: 8.7,
      y: 6.55,
      w: 3.6,
      h: 0.3,
      fontFace: BODY_FONT,
      fontSize: 10,
      color: "94A3B8",
      align: "right",
      margin: 0,
    });
  };

  // ============================================================
  // CONTENT SLIDE (router: bullets / two-column / stat / quote)
  // ============================================================

  const addContentSlide = (slideData, index, total) => {
    if (slideData?.quote) return addQuoteSlide(slideData, index, total);
    if (slideData?.stat) return addStatSlide(slideData, index, total);

    const slide = ppt.addSlide("MASTER");
    addTitle(
      slide,
      slideData?.title || `Section ${index}`,
      null,
      `Section ${index}`,
    );

    const bullets = Array.isArray(slideData?.bullets) ? slideData.bullets : [];

    if (!bullets.length) {
      slide.addText("No content available.", {
        x: 0.9,
        y: 2,
        w: 10,
        h: 0.5,
        fontFace: BODY_FONT,
        fontSize: 16,
        color: THEME.muted,
        margin: 0,
      });
      addSlideNumber(slide, index, total);
      return;
    }

    if (bullets.length > 5) {
      addTwoColumnBullets(slide, bullets, 1.95, 4.6);
    } else {
      addBadgeBullets(slide, bullets, 1.95, 4.6);
    }

    addSlideNumber(slide, index, total);
  };

  // ============================================================
  // SUMMARY SLIDE
  // ============================================================

  const addSummarySlide = () => {
    const slide = ppt.addSlide("MASTER");
    addTitle(slide, "Key Takeaways", null, "Summary");

    const slides = data?.slides || [];
    const takeaways = slides.flatMap((s) => s?.bullets || []).slice(0, 5);

    if (takeaways.length) {
      addBadgeBullets(slide, takeaways, 1.95, 4.6);
    }

    addSlideNumber(slide, slides.length + 1, slides.length + 1);
  };

  // ============================================================
  // THANK YOU
  // ============================================================

  const addThankYou = () => {
    const slide = ppt.addSlide();
    slide.background = { color: THEME.dark };

    slide.addText("Thank You", {
      x: 1,
      y: 2.45,
      w: 11.3,
      h: 0.8,
      fontFace: HEAD_FONT,
      fontSize: 38,
      bold: true,
      color: THEME.white,
      align: "center",
      margin: 0,
    });

    slide.addText("Generated with VortexAI", {
      x: 1,
      y: 3.5,
      w: 11.3,
      h: 0.4,
      fontFace: BODY_FONT,
      fontSize: 14,
      color: "94A3B8",
      align: "center",
      margin: 0,
    });

    slide.addText("AI-powered • Structured • Professional", {
      x: 1,
      y: 6.3,
      w: 11.3,
      h: 0.3,
      fontFace: BODY_FONT,
      fontSize: 9,
      color: "64748B",
      align: "center",
      margin: 0,
    });
  };

  // ============================================================
  // BUILD
  // ============================================================

  addCover();

  const slides = data?.slides || [];
  slides.forEach((slideData, index) => {
    addContentSlide(slideData, index + 1, slides.length + 1);
  });

  addSummarySlide();
  addThankYou();

  return ppt;
};
