// import PDFDocument, { moveDown } from "pdfkit";

// export const generatePdf = async (data) => {
//   return new Promise((resolve, reject) => {
//     const doc = new PDFDocument({
//       size: "A4",
//       margin: 50,
//       info: {
//         Author: "VortexAi",
//         Title: "data.title",
//         Creator: "VortexAi",
//       },
//     });

//     const chunks = [];

//     doc.on("data", (chunk) => chunks.push(chunk));
//     doc.on("end", () => resolve(Buffer.concat(chunks)));
//     doc.on("error", () => reject);

//     // Title
//     doc
//       .fontSize(28)
//       .text(data.title, {
//         align: "center",
//       })
//       .fillColor("#111827");

//     if (data.subtitle) {
//       doc.moveDown(1);
//     }

//     //Subtitle
//     doc
//       .fontSize(14)
//       .text(data.subtitle, {
//         align: "center",
//       })
//       .fillColor("#6B7280");

//     doc.moveDown(2);

//     data?.sections?.array.forEach((s) => {
//       doc.fontSize(18).text(s.heading, {}).fillColor("#111827");

//       doc.moveDown(1);

//       s?.points?.forEach((p) => {
//         doc
//           .fontSize(12)
//           .text("● " + p, {
//             lineGap: 5,
//           })
//           .fillColor("#374151");
//       });

//       doc.moveDown(1)

//     });

//     //footer

//      doc.moveDown(1)

//         doc
//       .fontSize(10)
//       .text("Generated By Vortex Ai",{
//         align:center
//       })
//       .fillColor("#9CA3AF");

//       doc.end()

//   });
// };


import PDFDocument from "pdfkit";

const COLOR = {
  title: "#111827",
  heading: "#111827",
  text: "#374151",
  muted: "#6B7280",
  rule: "#E5E7EB",
};

const FONT = {
  title: 22,
  subtitle: 11.5,
  heading: 13.5,
  text: 10.5,
  footer: 8.5,
};

const MARGIN = { top: 60, bottom: 55, left: 56, right: 56 };

export const generatePdf = (data = {}) =>
  new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margins: MARGIN,
        bufferPages: true,
        info: {
          Title: data.title || "Document",
          Subject: data.subtitle || "",
          Author: "VortexAI",
          Creator: "VortexAI",
        },
      });

      const chunks = [];
      doc.on("data", (c) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const width = doc.page.width - MARGIN.left - MARGIN.right;
      const bottomLimit = doc.page.height - MARGIN.bottom;

      const ensureSpace = (neededHeight) => {
        if (doc.y + neededHeight > bottomLimit) doc.addPage();
      };

      // ---- Title ----
      doc
        .font("Helvetica-Bold")
        .fontSize(FONT.title)
        .fillColor(COLOR.title)
        .text(data.title || "Untitled Document", { width });

      if (data.subtitle) {
        doc.moveDown(0.25);
        doc
          .font("Helvetica")
          .fontSize(FONT.subtitle)
          .fillColor(COLOR.muted)
          .text(data.subtitle, { width });
      }

      doc.moveDown(0.5);
      doc
        .strokeColor(COLOR.rule)
        .lineWidth(1)
        .moveTo(MARGIN.left, doc.y)
        .lineTo(doc.page.width - MARGIN.right, doc.y)
        .stroke();
      doc.moveDown(0.75);

      // ---- Block renderers ----
      const heading = (text) => {
        ensureSpace(FONT.heading + 20);
        doc.moveDown(0.6);
        doc
          .font("Helvetica-Bold")
          .fontSize(FONT.heading)
          .fillColor(COLOR.heading)
          .text(text || "", { width });
        doc.moveDown(0.25);
      };

      const paragraph = (text) => {
        doc
          .font("Helvetica")
          .fontSize(FONT.text)
          .fillColor(COLOR.text)
          .text(text || "", { width, lineGap: 2 });
        doc.moveDown(0.3);
      };

      const list = (items = [], ordered) => {
        items.forEach((item, i) => {
          const marker = ordered ? `${i + 1}.` : "\u2022";
          doc
            .font("Helvetica")
            .fontSize(FONT.text)
            .fillColor(COLOR.text)
            .text(`${marker}  ${item}`, { width, lineGap: 2 });
        });
        doc.moveDown(0.3);
      };

      const renderers = {
        heading: (b) => heading(b.text),
        paragraph: (b) => paragraph(b.text),
        bullets: (b) => list(b.items, false),
        numbered: (b) => list(b.items, true),
      };

      (Array.isArray(data.blocks) ? data.blocks : []).forEach((b) => {
        renderers[b?.type]?.(b);
      });

      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);

        const originalBottomMargin = doc.page.margins.bottom;
        doc.page.margins.bottom = 0;

        doc
          .font("Helvetica")
          .fontSize(FONT.footer)
          .fillColor(COLOR.muted)
          .text(`${i + 1}`, MARGIN.left, doc.page.height - 34, {
            width,
            align: "center",
            lineBreak: false,
          });

        doc.page.margins.bottom = originalBottomMargin;
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
